name: Build and Test

on:
  pull_request: {}
  push: { branches: [master] }

jobs:
  buildAndTest:
    name: Test against ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.3.11f1
        include:
          - unityVersion: 2019.3.11f1
            projectPath: test-project-2019.3
            licenseSecret: UNITY_LICENSE_2019_3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.7
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
        env:
          UNITY_LICENSE: ${{ secrets[matrix.licenseSecret] }}

      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: artifacts

      # # TODO: We'll have to tweak how we're recording test results once we setup
      # # multiple tests projects:
      # # https://github.com/marketplace/actions/publish-unit-test-results#use-with-matrix-strategy
      # - name: Publish Unit Test Results
      #   uses: EnricoMi/publish-unit-test-result-action@v1.5
      #   if: always()
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     files: artifacts/*.xml

      - name: Record Test Results
        uses: zyborg/dotnet-tests-report@v1.2.0
        with:
          report_name: all_tests
          report_title: All Tests
          test_results_path: artifacts/editmode-results.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}

  checkFormatting:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.403

      - name: Problem Matcher for dotnet-format
        uses: xt0rted/dotnet-format-problem-matcher@v1.2.0

      - run: dotnet tool install -g dotnet-format
      - run: dotnet format . --folder --check --exclude test-project-2019.3\Library
